import type { ThemeDefinition } from "../types";

function theme(def: ThemeDefinition): ThemeDefinition {
  return def;
}

export const classicNavy = theme({
  id: "classic_navy",
  name: "Classic Navy",
  description: "Conservative corporate style",
  fonts: { heading: "Georgia", body: "Georgia" },
  sizes: { name: 26, sectionHeading: 12, roleTitle: 11, body: 10.5, small: 9 },
  colors: {
    name: "#1F3864",
    accent: "#1F3864",
    heading: "#1F3864",
    body: "#1A1A1A",
    rule: "#1F3864",
    link: "#1F3864",
  },
  nameAlign: "center",
  nameCase: "normal",
  sectionHeadingCase: "upper",
  sectionRule: "full",
  nameRule: "full",
  nameBand: false,
  bulletGlyph: "•",
  spacing: { line: 1.08, paraAfter: 4, sectionBefore: 10 },
  margins: { top: 0.7, bottom: 0.7, left: 0.8, right: 0.8 },
});

export const modernSage = theme({
  id: "modern_sage",
  name: "Modern Sage",
  description: "Clean modern style",
  fonts: { heading: "Trebuchet MS", body: "Trebuchet MS" },
  sizes: { name: 30, sectionHeading: 13, roleTitle: 11, body: 10.5, small: 9 },
  colors: {
    name: "#4F6F52",
    accent: "#4F6F52",
    heading: "#4F6F52",
    body: "#222222",
    rule: "#C8D2C2",
    link: "#4F6F52",
  },
  nameAlign: "left",
  nameCase: "normal",
  sectionHeadingCase: "title",
  sectionRule: "short",
  nameRule: "full",
  nameBand: false,
  bulletGlyph: "▪",
  spacing: { line: 1.1, paraAfter: 4, sectionBefore: 10 },
  margins: { top: 0.7, bottom: 0.7, left: 0.85, right: 0.85 },
});

export const minimalMono = theme({
  id: "minimal_mono",
  name: "Minimal Mono",
  description: "Ultra-clean ATS-safe",
  fonts: { heading: "Arial", body: "Arial" },
  sizes: { name: 24, sectionHeading: 11, roleTitle: 11, body: 10.5, small: 9 },
  colors: {
    name: "#333333",
    accent: "#333333",
    heading: "#333333",
    body: "#333333",
    rule: "#BBBBBB",
    link: "#333333",
  },
  nameAlign: "left",
  nameCase: "upper",
  sectionHeadingCase: "upper",
  sectionRule: "full",
  nameRule: "full",
  nameBand: false,
  bulletGlyph: "–",
  spacing: { line: 1.12, paraAfter: 4, sectionBefore: 9 },
  margins: { top: 0.75, bottom: 0.75, left: 0.9, right: 0.9 },
});

export const executiveBurgundy = theme({
  id: "executive_burgundy",
  name: "Executive Burgundy",
  description: "Formal senior style",
  fonts: { heading: "Times New Roman", body: "Times New Roman" },
  sizes: { name: 26, sectionHeading: 12, roleTitle: 11, body: 10.5, small: 9 },
  colors: {
    name: "#6E1423",
    accent: "#6E1423",
    heading: "#6E1423",
    body: "#1A1A1A",
    rule: "#6E1423",
    link: "#6E1423",
  },
  nameAlign: "center",
  nameCase: "normal",
  sectionHeadingCase: "upper",
  sectionRule: "full",
  nameRule: "full",
  nameBand: false,
  bulletGlyph: "•",
  spacing: { line: 1.1, paraAfter: 4, sectionBefore: 10 },
  margins: { top: 0.7, bottom: 0.7, left: 0.85, right: 0.85 },
});

export const techSlate = theme({
  id: "tech_slate",
  name: "Tech Slate",
  description: "Developer-friendly density",
  fonts: { heading: "Verdana", body: "Verdana" },
  sizes: { name: 28, sectionHeading: 12, roleTitle: 11, body: 10, small: 8.5 },
  colors: {
    name: "#2C5F6F",
    accent: "#2C5F6F",
    heading: "#2C5F6F",
    body: "#1F1F1F",
    rule: "#B7C9CE",
    link: "#2C5F6F",
  },
  nameAlign: "left",
  nameCase: "normal",
  sectionHeadingCase: "upper",
  sectionRule: "short",
  nameRule: "full",
  nameBand: false,
  bulletGlyph: "»",
  spacing: { line: 1.06, paraAfter: 3, sectionBefore: 9 },
  margins: { top: 0.65, bottom: 0.65, left: 0.8, right: 0.8 },
});

export const compactPro = theme({
  id: "compact_pro",
  name: "Compact Pro",
  description: "Tight spacing for long careers",
  fonts: { heading: "Tahoma", body: "Tahoma" },
  sizes: { name: 24, sectionHeading: 11, roleTitle: 10.5, body: 10, small: 8.5 },
  colors: {
    name: "#27406B",
    accent: "#27406B",
    heading: "#27406B",
    body: "#202020",
    rule: "#27406B",
    link: "#27406B",
  },
  nameAlign: "left",
  nameCase: "normal",
  sectionHeadingCase: "upper",
  sectionRule: "none",
  nameRule: "full",
  nameBand: false,
  bulletGlyph: "•",
  spacing: { line: 1.0, paraAfter: 2, sectionBefore: 7 },
  margins: { top: 0.55, bottom: 0.55, left: 0.7, right: 0.7 },
});

export const bandedIndigo = theme({
  id: "banded_indigo",
  name: "Banded Indigo",
  description: "Design-forward header band",
  fonts: { heading: "Trebuchet MS", body: "Trebuchet MS" },
  sizes: { name: 28, sectionHeading: 12, roleTitle: 11, body: 10.5, small: 9 },
  colors: {
    name: "#FFFFFF",
    accent: "#34406B",
    heading: "#34406B",
    body: "#222222",
    rule: "#34406B",
    link: "#34406B",
  },
  nameAlign: "left",
  nameCase: "normal",
  sectionHeadingCase: "upper",
  sectionRule: "none",
  nameRule: "none",
  nameBand: true,
  bulletGlyph: "◦",
  spacing: { line: 1.1, paraAfter: 4, sectionBefore: 10 },
  margins: { top: 0.6, bottom: 0.7, left: 0.85, right: 0.85 },
});

export const elegantGaramond = theme({
  id: "elegant_garamond",
  name: "Elegant Garamond",
  description: "Refined editorial style",
  fonts: { heading: "Georgia", body: "Georgia" },
  sizes: { name: 28, sectionHeading: 12, roleTitle: 11, body: 11, small: 9.5 },
  colors: {
    name: "#2B2B2B",
    accent: "#8A6D3B",
    heading: "#2B2B2B",
    body: "#2B2B2B",
    rule: "#8A6D3B",
    link: "#8A6D3B",
  },
  nameAlign: "center",
  nameCase: "normal",
  sectionHeadingCase: "upper",
  sectionRule: "short",
  nameRule: "full",
  nameBand: false,
  bulletGlyph: "•",
  spacing: { line: 1.12, paraAfter: 4, sectionBefore: 11 },
  margins: { top: 0.8, bottom: 0.8, left: 0.9, right: 0.9 },
});
