import type { ResumeTemplate } from "../types";

function template(def: ResumeTemplate): ResumeTemplate {
  return def;
}

const DEFAULT_EDUCATION = ["Bachelors in Computer Science,"];

export const kishanBa = template({
  id: "kishan_ba",
  name: "Kishan BA",
  description: "Centered header, profile band, Bell MT body",
  sectionOrder: ["profile", "summary", "skills", "education", "experience"],
  sectionLabels: {
    profile: "PROFILE",
    summary: "SUMMARY",
    skills: "TECHNICAL SKILLS",
    education: "EDUCATION",
    experience: "WORK EXPERIENCE",
  },
  summaryHeading: true,
  splitProfileSummary: true,
  header: "kishan",
  sectionHeading: "kishan_band",
  skills: "paragraph",
  experience: "kishan",
  educationDefault: DEFAULT_EDUCATION,
  fonts: { heading: "Times New Roman", body: "Bell MT" },
  colors: {
    name: "#000000",
    role: "#000000",
    contact: "#000000",
    heading: "#000000",
    body: "#000000",
    accent: "#000000",
    duration: "#000000",
    rule: "#000000",
    sectionShading: "#E7E6E6",
  },
  sizes: { name: 20, role: 11, contact: 11, sectionHeading: 11, body: 10.5 },
  margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.5 },
  lineSpacing: 12,
  bulletGlyph: "•",
});

export const akhilDataEngineer = template({
  id: "akhil_data_engineer",
  name: "Akhil Data Engineer",
  description: "Left purple header, certifications, date-first roles",
  sectionOrder: ["summary", "skills", "certifications", "experience", "education"],
  sectionLabels: {
    skills: "Skills",
    certifications: "CERTIFICATIONS:",
    experience: "Experience",
    education: "Education",
  },
  summaryHeading: false,
  splitProfileSummary: false,
  header: "akhil_data",
  sectionHeading: "plain",
  skills: "paragraph",
  experience: "akhil_data",
  certifications: [
    "AWS Certified Solutions Architect Associate",
    "Azure Certified Data Engineer Associate",
    "Databricks Certified Data Engineer Associate",
  ],
  educationDefault: DEFAULT_EDUCATION,
  fonts: { heading: "Calibri", body: "Calibri" },
  colors: {
    name: "#7050A0",
    role: "#000000",
    contact: "#000000",
    heading: "#000000",
    body: "#000000",
    accent: "#7050A0",
    duration: "#7030A0",
    rule: "#000000",
    sectionShading: "#FFFFFF",
  },
  sizes: { name: 26, role: 20, contact: 11, sectionHeading: 11, body: 11 },
  margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.5 },
  lineSpacing: 12,
  bulletGlyph: "•",
});

export const akhilJava = template({
  id: "akhil_java",
  name: "Akhil Java",
  description: "Purple underline headings, bordered skills table",
  sectionOrder: ["summary", "skills", "experience", "education"],
  sectionLabels: {
    summary: "PROFESSIONAL SUMMARY:",
    skills: "TECHNICAL SKILLS:",
    experience: "PROFESSIONAL EXPERIENCE:",
    education: "EDUCATION:",
  },
  summaryHeading: true,
  splitProfileSummary: false,
  header: "akhil_java",
  sectionHeading: "purple_underline",
  skills: "table_bordered",
  experience: "akhil_java",
  educationDefault: DEFAULT_EDUCATION,
  fonts: { heading: "Calibri", body: "Calibri" },
  colors: {
    name: "#000000",
    role: "#000000",
    contact: "#000000",
    heading: "#6F2F9F",
    body: "#333333",
    accent: "#6F2F9F",
    duration: "#6F2F9F",
    rule: "#6F2F9F",
    sectionShading: "#FFFFFF",
  },
  sizes: { name: 19, role: 10.5, contact: 8.5, sectionHeading: 10.5, body: 10.5 },
  margins: { top: 0.611, bottom: 0.194, left: 0.403, right: 0.403 },
  lineSpacing: 12,
  bulletGlyph: "•",
});

export const vasuCpp = template({
  id: "vasu_cpp",
  name: "Vasu C++",
  description: "Centered blue header, bordered skills table",
  sectionOrder: ["summary", "skills", "experience"],
  sectionLabels: {
    summary: "PROFESSIONAL SUMMARY",
    skills: "TECHNICAL SKILLS",
    experience: "WORK EXPERIENCE",
  },
  summaryHeading: true,
  splitProfileSummary: false,
  header: "vasu",
  sectionHeading: "blue_rule",
  skills: "table_bordered",
  experience: "vasu",
  educationDefault: DEFAULT_EDUCATION,
  fonts: { heading: "Calibri", body: "Calibri" },
  colors: {
    name: "#1A1A2E",
    role: "#1F5C99",
    contact: "#555555",
    heading: "#1F5C99",
    body: "#000000",
    accent: "#1F5C99",
    duration: "#2F5496",
    rule: "#1F5C99",
    sectionShading: "#FFFFFF",
  },
  sizes: { name: 20, role: 15, contact: 12, sectionHeading: 11, body: 11 },
  margins: { top: 0.625, bottom: 0.625, left: 0.75, right: 0.75 },
  lineSpacing: 12,
  bulletGlyph: "•",
});

export const jayanthBa = template({
  id: "jayanth_ba",
  name: "Jayanth BA",
  description: "Arial layout, red role title, client/role experience lines",
  sectionOrder: ["summary", "skills", "education", "experience"],
  sectionLabels: {
    summary: "SUMMARY",
    skills: "TECHNICAL SKILLS",
    education: "EDUCATION",
    experience: "WORK EXPERIENCE",
  },
  summaryHeading: true,
  splitProfileSummary: false,
  header: "jayanth",
  sectionHeading: "arial_bold",
  skills: "paragraph",
  experience: "jayanth",
  educationDefault: DEFAULT_EDUCATION,
  fonts: { heading: "Arial", body: "Arial" },
  colors: {
    name: "#000000",
    role: "#EE0000",
    contact: "#000000",
    heading: "#000000",
    body: "#0D0D0D",
    accent: "#EE0000",
    duration: "#000000",
    rule: "#000000",
    sectionShading: "#FFFFFF",
  },
  sizes: { name: 24, role: 14, contact: 10, sectionHeading: 11, body: 12 },
  margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.5 },
  lineSpacing: 12,
  bulletGlyph: "•",
});

export const keerthanaServicenow = template({
  id: "keerthana_servicenow",
  name: "Keerthana ServiceNow",
  description: "Table header, certifications, tab-aligned dates",
  sectionOrder: ["summary", "education", "certifications", "skills", "experience"],
  sectionLabels: {
    summary: "Summary",
    education: "Education",
    certifications: "Certifications",
    skills: "Skills & Abilities",
    experience: "Experience",
  },
  summaryHeading: true,
  splitProfileSummary: false,
  header: "keerthana_table",
  sectionHeading: "plain",
  skills: "paragraph",
  experience: "keerthana",
  certifications: [
    "Servicenow Certified System Administrator",
    "Servicenow Certified Application Developer",
    "Micro-certifications: Agentic AI Executive, Predictive Intelligence",
  ],
  educationDefault: ["Osmania University | Hyd |2016"],
  fonts: { heading: "Calibri", body: "Calibri" },
  colors: {
    name: "#000000",
    role: "#000000",
    contact: "#000000",
    heading: "#000000",
    body: "#0D0D0D",
    accent: "#000000",
    duration: "#000000",
    rule: "#000000",
    sectionShading: "#FFFFFF",
  },
  sizes: { name: 12, role: 11, contact: 11, sectionHeading: 11, body: 10.5 },
  margins: { top: 0.25, bottom: 0.5, left: 0.5, right: 0.5 },
  lineSpacing: 12,
  bulletGlyph: "•",
});

export const ALL_TEMPLATES = [
  kishanBa,
  akhilDataEngineer,
  akhilJava,
  vasuCpp,
  jayanthBa,
  keerthanaServicenow,
];
